import type { Agent } from '@core/types'

/** Sample agents for Playground testing. */
export const CHARACTERS_DEFAULTS: Agent[] = [
  {
    id: 'protagonist',
    name: 'Wu Concubine',
    chineseName: '武氏嫔妃',
    portraitId: 'protagonist-default',
    tier: 'silver',
    isProtagonist: true,
    tags: ['noble', 'protagonist'],
    conditions: [],
    stats: {
      beauty: 6,
      cunning: 3,
      eloquence: 4,
      discretion: 2,
      resolve: 2,
      vitality: 2,
      resourcefulness: 1,
      spiritualArts: 1,
      scholarship: 1,
    },
  },
  {
    id: 'chunhua',
    name: 'Chunhua',
    chineseName: '春花',
    portraitId: 'chunhua',
    tier: 'bronze',
    tags: ['maid', 'noble'],
    conditions: [],
    resentment: 0,
    stats: {
      beauty: 2,
      cunning: 3,
      eloquence: 2,
      discretion: 3,
      resolve: 2,
      vitality: 2,
      resourcefulness: 2,
      spiritualArts: 1,
      scholarship: 1,
    },
  },
  {
    id: 'guard-luo',
    name: 'Sergeant Luo',
    chineseName: '罗侍卫',
    portraitId: 'guard-luo',
    tier: 'bronze',
    tags: ['guard'],
    conditions: [],
    stats: {
      beauty: 1,
      cunning: 1,
      eloquence: 1,
      discretion: 1,
      resolve: 3,
      vitality: 3,
      resourcefulness: 2,
      spiritualArts: 0,
      scholarship: 0,
      martial: 2,
    },
  },
]
